name: Linter Python

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clonage du dépot
        uses: actions/checkout@v3.5.2


      - name: Installation de python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --config ./setup.cfg
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --statistics --config ./setup.cfg

      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.0.239
